# Generated by Django 5.2.1 on 2025-06-07 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecturer', '0002_lecturerprofile_assigned_kumpulan_classmaterial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturerprofile',
            name='field_of_expertise',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
