# Generated by Django 5.2.1 on 2025-06-05 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kumpulan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='kumpulan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.kumpulan'),
        ),
    ]
