# Generated by Django 5.2.1 on 2025-06-05 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_kumpulan_alter_studentprofile_kumpulan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='kumpulan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.kumpulan'),
        ),
    ]
