# Generated by Django 5.2 on 2025-05-18 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_studentprofile_alter_milestone_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestone',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
